### ISSUE TITLE
2.5 Road map

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [mhtvsSFrpHdE/prefetch#24]
- [x] Fix tray icon still appears after exit
- [x] Exit tray menu
- [x] Very demo quality window application
  - [x] In order to hide window, no console anymore
  - [ ] Lacking custom font size
  - [ ] Lacking high dpi scale
- [x] Minimize to tray
- [x] Double-click on tray icon to show or hide console
- [x] Start with console or only tray icon
