### ISSUE TITLE
 2.6 Road map

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [mhtvsSFrpHdE/prefetch#34]
- [x] Fix MainWindow not update immediately to reflect background updates 03864aba6b263379a9b903882e62aee5126d62d8
- [x] Custom font size a0ccd2498c03be967df79cc0eee50985ea7ebd4c
- [x] Custom font family a0ccd2498c03be967df79cc0eee50985ea7ebd4c
- [x] DPI scale dd581875c1c919dda45efb93803764edc3fc3657
