### ISSUE TITLE
2.7 Road map

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [mhtvsSFrpHdE/prefetch#38]
- [x] **WARNING**: Drop support for fuzzy config, remove hard-coded default value  
 If a config value failed to parse, no code to handle this situation anymore  
 Assume config is always correct 87a783a47afebd39b98a5728f0e916de7b418a5b
- [x] New config PrintOffset to optimal console looking c2eb933d3e0a8d3f5e95fe541538efc4636a07d5
- [x] Show last line of stdout in tray menu 57ebf4d4f55d9ee262b274d1d8e1f1f0fa00410b
- [x] Tray menu: click on instance name or last line of stdout will treat as double-click on tray icon a5b1de629be4e5536e7cc21dfe3451bfbcc1a10a
