### ISSUE TITLE
2.7.1 Road map

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [mhtvsSFrpHdE/prefetch#40]
- [x] Fix scrollbar position when mainwindow hide->show
- [x] Fix right click on tray icon can crash in early loading process
- [x] Const command table
- [x] Safe exit
 Check why default thread pool can cause program lost response, maybe create another one
