### ISSUE TITLE
4.1 Road map

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [mhtvsSFrpHdE/prefetch#68]
- [x] Fix scan folder sec lack translate 1c2d492221ea8843dd22111697ff0eb793430b89
- [x] #64 4ff199cdec7059ebca52f80e039dba4de9a91409
- [x] Rename `pause` and `resume` command to `stop` and `start` d4a0812a4acd0534cff6c0ec162f98f69fe716d8  
  When `pause` requested, this program does not reserve intermediate run state.  
  And when request `resume`, prefetch will run from beginning,  
  and run immediately (discard unfinished prefetch interval).  
  You can also type `resume` without have to type `pause` first.  
  Therefore, this should be called `stop` and `start`.  
  <br>Due to no longer provided `pause` and `resume` command,
  This change breaks forward compatible, but is not a giant feature pack.  
  So version number will increase to `4.1` instead of `5.0`.
- [x] Update command interface wiki page about stop and start  
  Move pause and resume to deprecated command
- [x] Fix source code with same name in different folder "multiple definition" 6fdad942dcea062d7fbe6dd8bf57712f928cc7d5  
  Maintenance update
- [x] #65
