### ISSUE TITLE
4.5 Road map

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [mhtvsSFrpHdE/prefetch#72]
- [x] #73 ff4af54d32556d85eb071b14355db837a8d8e16d
- [x] Move startup item code to command 7502280d0846e421c9151cd6eb2d755e0cb16a69
- [x] Send multiple command at once to receiveText bbd1e60b50c037d4aa0f2b6b7097f5a27230bd2b
